param(
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$utf8Strict = New-Object System.Text.UTF8Encoding($false, $true)
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$webDir = $PSScriptRoot
$rootDir = Split-Path -Parent $webDir
$outputPath = Join-Path $rootDir "src\dashboard_embedded.generated.h"

function Read-NormalizedText([string]$path) {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    return $utf8Strict.GetString($bytes).Replace("`r`n", "`n").Replace("`r", "`n")
}

function Replace-ExactlyOnce([string]$text, [string]$marker, [string]$replacement) {
    $first = $text.IndexOf($marker, [System.StringComparison]::Ordinal)
    if ($first -lt 0 -or $text.IndexOf($marker, $first + $marker.Length, [System.StringComparison]::Ordinal) -ge 0) {
        throw "Expected exactly one $marker marker in web/index.html"
    }
    return $text.Substring(0, $first) + $replacement + $text.Substring($first + $marker.Length)
}

$template = (Read-NormalizedText (Join-Path $webDir "index.html")).TrimEnd([char[]]"`n")
$styles = (Read-NormalizedText (Join-Path $webDir "styles.css")).TrimEnd([char[]]"`n")
$script = (Read-NormalizedText (Join-Path $webDir "app.js")).TrimEnd([char[]]"`n")
$iconsSource = (Read-NormalizedText (Join-Path $webDir "icons.svg")).Trim()

$iconsMatch = [System.Text.RegularExpressions.Regex]::Match(
    $iconsSource,
    '^<svg\b[^>]*>(?<content>.*)</svg>$',
    [System.Text.RegularExpressions.RegexOptions]::Singleline
)
if (-not $iconsMatch.Success) {
    throw "web/icons.svg must contain one SVG root element"
}
$iconsContent = $iconsMatch.Groups["content"].Value.Trim()
$inlineIcons = ""
if ($iconsContent.Length -gt 0) {
    $inlineIcons = '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">' + $iconsContent + "</svg>`n"
}

$bundle = Replace-ExactlyOnce $template "{{KEYSIDEKICK_STYLES}}" $styles
$bundle = Replace-ExactlyOnce $bundle "{{KEYSIDEKICK_SCRIPT}}" $script
$bundle = Replace-ExactlyOnce $bundle "{{KEYSIDEKICK_ICONS}}" $inlineIcons

if ($bundle.IndexOf([char]0) -ge 0) {
    throw "Dashboard bundle cannot contain NUL bytes"
}
if ($bundle -match '(?i)(?:src|href)\s*=\s*["'']\s*(?:https?:)?//' -or $bundle -match '(?i)@import\s+.*(?:https?:)?//') {
    throw "Dashboard bundle must not reference remote assets"
}

$bundleBytes = $utf8NoBom.GetBytes($bundle)
$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("#pragma once")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("// Generated by web/generate_dashboard.ps1. Do not edit manually.")
[void]$builder.AppendLine("static const char kDashboardHtml[] =")
for ($offset = 0; $offset -lt $bundleBytes.Length; $offset += 32) {
    [void]$builder.Append('    "')
    $lineEnd = [Math]::Min($offset + 32, $bundleBytes.Length)
    for ($index = $offset; $index -lt $lineEnd; $index++) {
        $octal = [Convert]::ToString($bundleBytes[$index], 8).PadLeft(3, '0')
        [void]$builder.Append('\' + $octal)
    }
    [void]$builder.AppendLine('"')
}
[void]$builder.AppendLine("    ;")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("static const size_t kDashboardHtmlSize = sizeof(kDashboardHtml) - 1;")
$generated = $builder.ToString().Replace("`r`n", "`n")
$generatedBytes = $utf8NoBom.GetBytes($generated)

$matches = $false
if ([System.IO.File]::Exists($outputPath)) {
    $existingBytes = [System.IO.File]::ReadAllBytes($outputPath)
    $matches = $existingBytes.Length -eq $generatedBytes.Length
    if ($matches) {
        for ($index = 0; $index -lt $existingBytes.Length; $index++) {
            if ($existingBytes[$index] -ne $generatedBytes[$index]) {
                $matches = $false
                break
            }
        }
    }
}

if ($Check) {
    if (-not $matches) {
        [Console]::Error.WriteLine("Generated dashboard resource is stale: $outputPath")
        exit 1
    }
    Write-Host "Dashboard resource is up to date."
    exit 0
}

if (-not $matches) {
    [System.IO.File]::WriteAllBytes($outputPath, $generatedBytes)
    Write-Host "Generated dashboard resource: $outputPath"
} else {
    Write-Host "Dashboard resource already up to date."
}
